txt = "test \"text\""
integer = 12345
int_array = [1,2,3,4,5]
string_array = ["a","b","c","d","e"]
multiline_array= [
	"a",
	"b",
	"c",
	"d",
	"\""
	]
double = 12.2

nested.a = 2
nested.b = "test"

[test]
txt = "more test text"
[testa]
txt = "even more test text"
[testa.blorp]
txt = "very nested text"

[[testc]]
txt = "text1"
[[testc]]
txt = "text2"
[testc.mem]
num = 2
[[testc]]
txt = "text3"