[basic]
text = "test text"
texts = ["this", "is", "a", "test", "text"]
number = 42
decnumber = 3.14

[basiclist]
name = "basic"
[[basiclist.list]]
text = "1"
texts = []
number = 1
decnumber = 1.1
[[basiclist.list]]
text = "2"
texts = []
number = 2
decnumber = 2.2
[[basiclist.list]]
text = "3"
texts = []
number = 3
decnumber = 3.3

[nestedlist]
name = "nested"

[[nestedlist.list]]
name = "nested1"
[[nestedlist.list.list]]
text = "4"
texts = []
number = 4
decnumber = 4.4
[[nestedlist.list.list]]
text = "5"
texts = []
number = 5
decnumber = 5.5


[[nestedlist.list]]
name = "nested2"
[[nestedlist.list.list]]
text = "6"
texts = []
number = 6
decnumber = 6.6
[[nestedlist.list.list]]
text = "7"
texts = ["nested", "test"]
number = 7
decnumber = 7.7

